# Generated by Django 3.0.4 on 2020-03-07 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Назва')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Власник курсу')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курси',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Назва')),
                ('start', models.TimeField(verbose_name='Початок заняття')),
                ('end', models.TimeField(verbose_name='Кінець заняття')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Група',
                'verbose_name_plural': 'Групи',
            },
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(editable=False, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField(editable=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Group', verbose_name='Група')),
            ],
            options={
                'verbose_name': 'Код верифікації',
                'verbose_name_plural': 'Коди верифікації',
            },
        ),
    ]
